### ISSUE TITLE
device_class is not working for icons

### ISSUE THREAD

**Issue by pepeEL** [estevez-dev/ha_client#237]
Hi
I have added to my HA by 1wire sensors of temp. I add it in lovelace in glance card. In HA web page show correct icon to temperature as termometer... but in app show icon EYE but should show termometer.

**Comment by estevez-dev** [comment]
The same can be reproduced for Xiaomi aqara sensor. Wrong icon in app.
_Need to check device_class or other params not in attributes_

**Comment by pepeEL** [comment]
It is as sensor.

**Comment by pepeEL** [comment]
Still is a problem...
![screenshot_20181214-111307](https://user-images.githubusercontent.com/16692223/49997427-d6917d80-ff91-11e8-8f86-d8c54caa9967.jpg)
I have two device in my HA connected by onewire. It is name/entity:
sensor.salon_temperature
sensor.sypialnia_temperature

and it has show in app with wrong icon. Not termometer. Show icon eye. For other sensors temperature show correct icon as termometer. But in web browser show correct icon. Only in your app is wrong.

**Comment by Kvasenok** [comment]
There is an icon missing for the timer entity. It's not a big deal since it can be replaced with a any other icon and it should solve the problem, but it is still a bug that needs to be fixed. 
I believe it is because of the same device_class issue, but I can be wrong. In this case I will open another issue.
![screenshot_20181217-014942_chrome](https://user-images.githubusercontent.com/44749170/50060056-d1098280-019f-11e9-8bc5-d5df6e4be6ab.jpg)
![screenshot_20181217-014910](https://user-images.githubusercontent.com/44749170/50060057-d1098280-019f-11e9-9de1-5b25af378ae5.jpg)

**Comment by estevez-dev** [comment]
@Kvasenok please create a separate issue for this. It is not depend on device_class. There is no icons for timer entity in app.

**Comment by pepeEL** [comment]
Why you closed all our issues. My issue is closed. I must again open new issue? This is no good because problem with icon temp for some sensors I still have...

**Comment by estevez-dev** [comment]
@pepeEL I fixed all the issues related to device_classes and icons. Your issue is a Home Assistant one. There is no way to figure out the right icon for some temperature sensors from Home Assistant API. I'll report this issue to Home Assistant repository.
