### ISSUE TITLE
Comodo SSL cert issue

### ISSUE THREAD

**Issue by gladdiieh** [estevez-dev/ha_client#344]
Unfortunately the app cannot connect to my home assistant due to a certificate verification error. I use a public wildcard certificate from Comodo and it seems that this CA or the sub CA isn't trusted by the app. The log shows "unable to get local issuer certificate(handshake.cc:352))"
Is there any workaround to get this fixed. Because disabling TLS isn't an option for me, I'm not able to use the app.

**Comment by JanSchnacki** [comment]
I think I have the same issue, just not with a Comodo certificate but with one created by mkcert. 

```
0407 22:19:15 [Debug] :  AppLifecycleState.inactive
0407 22:19:15 [Debug] :  AppLifecycleState.resumed
0407 22:19:15 [Debug] :  Use lovelace is true
0407 22:19:15 [Debug] :  Socket connecting...
0407 22:19:16 [Error] :  Socket stream Error: WebSocketChannelException: WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))
0407 22:19:16 [Debug] :  Automatic reconnect is false
```

**Comment by MTrab** [comment]
Not strictly Comodo SSL issue - I have the same issue with the same error, just on a wildcard AlphaSSL certificate.

**Comment by warrenseymour** [comment]
My solution to this issue was to have my Home Assistant server offer the full certificate chain. How you do that may vary between issuers, but in my case I created a file file that contained the original certificate, followed by the contents of the 'bundle' file that was included with it and then pointed my HA configuration against it.

**Comment by MTrab** [comment]
I'm serving a full chain (my cert, followed by the bundle in one file) - and that doesn't work.

**Comment by RockWest** [comment]
I'm having the same issue. I'm using a with a Let's Encrypt Authority X3 certificate using TLS 1.2

Chrome 74.0.3729.157 connects and accepts the SSL certificate through the browser on the same device running Android 9.

`0530 15:16:11 [Debug] :  Socket connecting...`
`0530 15:16:11 [Error] :  Socket stream Error: WebSocketChannelException:`
`WebSocketChannelException: HandshakeException: Handshake error in client (OS Error: `
`	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:352))`
`0530 15:16:11 [Debug] :  Automatic reconnect is false`
`0530 15:16:14 [Debug] :  Socket sink closed`


The app works really well without SSL. Very responsive and stable. I appreciate all your work on this and am eagerly anticipating device tracking and push notifications.

**Comment by urusha** [comment]
I'm getting the same error. With self created CA (added to trusted in android) and certificate signed by this CA with SAN - IP. Chrome accepts this certificated without issues.

**Comment by urusha** [comment]
@estevez-dev I saw your post https://community.home-assistant.io/t/beta-ha-client-native-android-client-for-home-assistant/69912/153 . May this be applied to your app: https://developer.android.com/training/articles/security-config ? 
According to it from API 24 there is no `<certificates src="user" />` in the default configuration. Could we add this to the default app configuration, since HA is about home, and home is self-made stuff (CAs in this case). Moreover Chrome accepts certificates from user's cert store.
Here is an example: https://github.com/flutter/plugins/blob/master/packages/video_player/example/android/app/src/main/res/xml/network_security_config.xml

**Comment by estevez-dev** [comment]
Thanks @urusha I'll try to add it for the 0.7.3 release

**Comment by naamah75** [comment]
Same issue with latest 0.7.3 ...

**Comment by estevez-dev** [comment]
This is sad. Will continue my investigations here.

**Comment by urusha** [comment]
@naamah75 that commit wasn't aimed to solve your issue, it was about mine. But that didn't work for me too. Seems there is another common issue with certificates.

**Comment by estevez-dev** [comment]
Merging this issue with #180
