### ISSUE TITLE
Can't change connection settings

### ISSUE THREAD

**Issue by klejejs** [estevez-dev/ha_client#358]
If you go to connection settings and change something that impacts the login, the error app throws is that it can't reconnect to server. It never asks to enter new login information.

**Comment by estevez-dev** [comment]
App need to connect to the server first to know do you need a login or is token not valid. I think this is how it should work.

**Comment by klejejs** [comment]
Well, the problem is that if I change the server, I don't get an option to also change the login information(username and password)

**Comment by estevez-dev** [comment]
1. You are logged in with some of your HA instance
2. You change connection settings in app pointing it to another HA instance
3. App connects to new HA instance
4. App has long-lived token, so it tries to login with it
5. New HA instance response with login error
6. App removes existing login-token and shows login error to user asking to login again

That's how it should work. If it can't connect to a new HA instance, then the issue is in connection, not in authentication.

**Comment by klejejs** [comment]
Oh, ok, understood. In that case, the case can be closed.
